#!/bin/bash
set -e
set -x
DATE="$(date +%Y%m%d_%H%M%S)"
git tag "deploy-${DATE}"
git push --tags
rm -rf .cache public __deploy
yarn gatsby build
yarn test
git clone "`git remote get-url origin`" __deploy
cd __deploy

if [ "$CI" != "" ]; then
  git config credential.helper "store --file=.git/credentials"
  echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > .git/credentials
fi;

git checkout master
cp -af ../public/* ./
echo 'www.graphile.org' > CNAME

git update-index -q --really-refresh
if ! git diff-index --exit-code --name-status HEAD --; then
  git add .
  git commit -m"Deploy $DATE"
  git push origin master
else
  echo "No changes to deploy"
fi
