#!/usr/bin/env node

const fs = require("fs");
const pg = require("pg");
const fetch = require("node-fetch");
const prettier = require("prettier");
const { graphql, parse } = require("graphql");
const child_process = require("child_process");
const {
  createPostGraphileSchema,
  withPostGraphileContext,
} = require("postgraphile");

async function prettify(filepath, content) {
  const options = await prettier.resolveConfig(filepath);
  return prettier.format(content, {
    ...options,
    printWidth: 50,
    filepath,
  });
}

async function spawn(command, args, options = {}, stdin = null) {
  return new Promise((resolve, reject) => {
    console.log(command, ...args);
    const cp = child_process.spawn(command, args, {
      stdio: "pipe",
      ...options,
    });
    let stdout = "";
    let stderr = "";
    cp.stdout.on("data", data => {
      stdout += data;
    });
    cp.stderr.on("data", data => {
      stderr += data;
    });
    cp.on("error", reject);
    function fail(e) {
      e.stdout = stdout;
      e.stderr = stderr;
      console.error(stderr);
      reject(e);
    }
    cp.on("close", code => {
      if (code === 0) {
        resolve({
          stdout,
          stderr,
          code,
        });
      } else {
        const e = new Error(`Failed with status code ${code}`);
        e.code = code;
        fail(e);
      }
    });
    if (stdin) {
      cp.stdin.on("error", fail);
      cp.stdin.write(stdin);
      cp.stdin.end();
    } else {
      cp.stdin.end();
    }
  });
}

async function psql(flags, sql) {
  return spawn(
    "psql",
    ["-X", "-1", "-v", "ON_ERROR_STOP=1", ...flags],
    {},
    sql
  );
}

async function main() {
  const schemaSql = await (await fetch(
    "https://raw.githubusercontent.com/graphile/examples/master/data/schema.sql"
  )).text();
  const dataSql = await (await fetch(
    "https://raw.githubusercontent.com/graphile/examples/master/db/999_data.sql"
  )).text();
  try {
    await spawn("dropdb", ["graphile_org_demo"]);
  } catch (e) {
    /* non-existence is fine */
  }
  await spawn("createdb", ["-O", "graphiledemo", "graphile_org_demo"]);
  await psql(["graphile_org_demo"], schemaSql);
  await psql(["graphile_org_demo"], dataSql);
  const pgPool = new pg.Pool({
    connectionString: "postgres://localhost/graphile_org_demo",
  });
  try {
    const postgraphileSchema = await createPostGraphileSchema(
      pgPool,
      ["app_public"],
      {
        dynamicJson: true,
      }
    );
    const queryPath = `${__dirname}/../examples/queries`;
    const directories = fs
      .readdirSync(queryPath)
      .filter(dir => fs.statSync(`${queryPath}/${dir}`).isDirectory());
    for (const dir of directories) {
      const dirPath = `${queryPath}/${dir}`;
      const outPath = `${__dirname}/../src/examples/${dir}`;
      await spawn("mkdir", ["-p", outPath]);
      const queries = fs
        .readdirSync(dirPath)
        .filter(f => f.match(/^[^.].*\.graphql$/));
      for (const queryFilename of queries) {
        const queryFilePath = `${dirPath}/${queryFilename}`;
        const query = fs.readFileSync(queryFilePath, "utf8");
        const { data, errors } = await withPostGraphileContext(
          {
            pgPool,
            pgSettings: {
              role: "graphiledemo_visitor",
              "jwt.claims.user_id": 1,
            },
          },
          context => graphql(postgraphileSchema, query, null, context)
        );
        if (errors && errors.length) {
          throw new Error("Errors occurred!" + String(errors));
        }
        const prettyQuery = await prettify(queryFilePath, query);
        const prettyData = await prettify(
          queryFilePath + ".json",
          JSON.stringify(data)
        );
        fs.writeFileSync(`${outPath}/${queryFilename}`, prettyQuery);
        fs.writeFileSync(
          `${outPath}/${queryFilename.replace(/graphql$/, "json")}`,
          prettyData
        );
      }
    }
  } finally {
    pgPool.end();
  }
}

main().then(null, error => {
  console.error(error);
  process.exit(1);
});
